name: '🍎 기능/오류 수정 이슈'
description: '중요한 기능 수정, 오류 수정 시 작성합니다.'
labels: [fix]
title: '🍎 이슈 제목'
assignees:
  - octocat
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎫 Parent Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'KAN-27'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📌 Description'
      description: '이슈에 대해서 상세히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Todo'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      placeholder: '- [ ] Task1'
    validations:
      required: false